// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARsQMnOn7WYR74_l95_iYsZL8DukaW85k',
    appId: '1:122528844362:web:2e0074f4672bce48f9f4b3',
    messagingSenderId: '122528844362',
    projectId: 'chat-app-3f663',
    authDomain: 'chat-app-3f663.firebaseapp.com',
    storageBucket: 'chat-app-3f663.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK5WX2AvWgM1sUbEYKqda2KYSGiH1vHNs',
    appId: '1:122528844362:android:c169d5a936c9d3aaf9f4b3',
    messagingSenderId: '122528844362',
    projectId: 'chat-app-3f663',
    storageBucket: 'chat-app-3f663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1U1-wXs1blFiVwXq1SrDKBSo7gq6GEjw',
    appId: '1:122528844362:ios:54bfef4315676b7ef9f4b3',
    messagingSenderId: '122528844362',
    projectId: 'chat-app-3f663',
    storageBucket: 'chat-app-3f663.appspot.com',
    iosBundleId: 'com.example.chatWithFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1U1-wXs1blFiVwXq1SrDKBSo7gq6GEjw',
    appId: '1:122528844362:ios:54bfef4315676b7ef9f4b3',
    messagingSenderId: '122528844362',
    projectId: 'chat-app-3f663',
    storageBucket: 'chat-app-3f663.appspot.com',
    iosBundleId: 'com.example.chatWithFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARsQMnOn7WYR74_l95_iYsZL8DukaW85k',
    appId: '1:122528844362:web:b137f5b30410ef8af9f4b3',
    messagingSenderId: '122528844362',
    projectId: 'chat-app-3f663',
    authDomain: 'chat-app-3f663.firebaseapp.com',
    storageBucket: 'chat-app-3f663.appspot.com',
  );
}
